### ISSUE TITLE
in project list, have a customizable button for link

### ISSUE THREAD

**Issue by KleiolabDK** [geovistory/toolbox#276]
Requirement:

- have an additional button that allows to link an external page.

![Image](https://github.com/geovistory/toolbox/assets/51605237/650c0968-b971-4df9-b402-25613f24a677)

- in the database, should have a field (text property) for the label of the button and another one for the URL
- this button should appear only if these fields are filled
- clicking on the button, a new tab should open
- potentially, also option to have 2 additional buttons
- option (if easy to program): have same button also appear on the top-left bar once the project is opened:

![Image](https://github.com/geovistory/toolbox/assets/51605237/08080bd7-bb11-4ead-a4ee-e12295ab9a0c)

**Comment by joschne** [comment]
Data

- [ ] add system type for pro text property:
  - project-link-1-label  
  - project-link-1-url
  - project-link-2-label  
  - project-link-2-url

Server

- [ ] Add the 4 new system types to the query that loads project list and project basics

Client

- [ ] Add selector for the 4 text properties
- [ ] Add buttons in gv-project-card in case link-1 and link-2 are configured
