### ISSUE TITLE
Add linguistic object in the content tree

### ISSUE THREAD

**Issue by joschne** [geovistory/toolbox#352]
**Current Situation**

In the content tree, it is currently possible to add Table, Text, and Section as child of an Expression.

<img width="1529" alt="Screenshot 2024-04-04 at 10 41 13" src="https://github.com/geovistory/toolbox/assets/49342191/d9beb74e-db51-4fc7-98ab-48c258dd7f86">

This is insufficient because some projects have linguistic objects that don't contain text. So the Text class does not meet the needs.

**Solution**

1. Content tree edit
1.a.
In the menu of Source Content and Section (and Linguistic Object once created), we need to add a button Linguistic Object, below Section but before Table and Text.
That creates a statement with:
subject: Clicked Instance (of class, Expression | Section | Linguistic Object)
property: crm:P165 incorporates
object: Linguistic Object
The button should be Blue (Entity) FOR THE MOMENT.

1.b. The Linguistic Object cannot be the parent of something else than a Text, Table or another Linguistic Object. Expressions and Expressions sections are NOT linguistic objects.

2. Content tree view
In the content tree visualize also property crm:P165 incorporates and its objects, as well as instances of geov:C16 Text (see issue #353) with the property geov:P1i is reproduced of

3. Show the content tree tab on entity cards of Linguistic Objects
On the View of Lingusitic Object, show the content tree on the right.

**Comment by joschne** [comment]
Resolved by [this commit](https://github.com/geovistory/toolbox/commit/b994d985e5c4da10c6ddf68838385e848d633a82) 
and toolbox configuration.

Can you please check and close this issue, if resolved @stephenhart8 ?

**Comment by stephenhart8** [comment]
All good for me, thank you all.
