### ISSUE TITLE
Bug displaying Expressions (Source Content) in the Container tab

### ISSUE THREAD

**Issue by stephenhart8** [geovistory/toolbox#377]
With the need to create Expressions (called Source Content in Geovistory Toolbox) without the physical support, with Francesco we tinkered with the addition of Expression in the create menu (by putting the class 218 on "true").
This caused the display of those Expressions in the Container tab in the Sources (and not in the Content tab).

To avoid any issues, the class 218 was put back as "false" in the creation menu, but this bug needs to be solved for a project in autumn 2025.

**Comment by dferhod** [comment]
Le problème semble se trouver dans ce fichier :
client/apps/app-toolbox/src/app/components/layout/left-drawer/components/sources-tabs/sources-tabs.component.ts

Il faudrait exclure de container les classes 218 et 503.
